<center> <h1>Universidad Nacional de San Agustín de Arequipa</h1> </center> 
<center> <h1>Escuela Profesional de Ingeniería de Telecomunicaciones</h1> </center> 

<center> <h1> </h1> </center> 

<center><img src="https://user-images.githubusercontent.com/19308295/115939517-f1c6fe80-a463-11eb-989c-812ab4942586.png" width="380" height="4200"></center>

<center> <h2>Ingeniero Renzo Bolivar - Docente DAIE</h2> </center> 

<center> <h1>Integrantes- Edwin Josue Cobarrubia Betancourt</h1> </center> 

<center> <h1>Curso : Computación 2</h1> </center> 

<center> <h1>NUMPY</h1> </center> 

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)

## <font color=#33A5FF>****EJERCICIOS****<tfont>

<center> <h2>Ejercicio 01</h2> </center> 

* Crear un array 7x8 lleno de ceros de tipo entero.


In [3]:
import numpy as np

# 1. Crear un array 7x8 lleno de ceros de tipo entero
array_zeros = np.zeros((7, 8), dtype=int)
print(array_zeros)


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


* Crear un array 7x8 lleno de ceros salvo la primera fila que serán todo unos.


In [5]:
array_ones_row = np.zeros((7, 8), dtype=int)
array_ones_row[0, :] = 1
print(array_ones_row)


[[1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


* Crear un array 7x8 lleno de ceros salvo la última fila que será el rango entre 5 y 8.

In [19]:
array_range_last_row = np.zeros((7, 8), dtype=int)
array_range_last_row[-1, :] = np.tile([5, 6, 7, 8], 2)  # Pero como solo hay 8 columnas, ajustamos el rango
print(array_range_last_row)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [5 6 7 8 5 6 7 8]]


<center> <h2>Ejercicio 02</h2> </center> 

* Crea un vector de 10 elementos, siendo los impares 1 y los pares 2.


In [26]:
ej2_1 = np.where(np.arange(10) % 2 == 0, 2, 1)

print("\nEjercicio 2.1:\n", ej2_1)




Ejercicio 2.1:
 [2 1 2 1 2 1 2 1 2 1]


* Crea un «tablero de ajedrez» 8x8, con 1 en las casillas negras y 0 en las casillas blancas.

In [31]:
ej2_2 = np.indices((8, 8)).sum(axis=0) % 2
print("\nEjercicio 2.2:\n", ej2_2)


Ejercicio 2.2:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


<center> <h2>Ejercicio 03</h2> </center> 

* Crea una matriz aleatoria 7x7 y halla los valores mínimo y máximo.


In [39]:
ej3 = np.random.randint(0, 100, (7, 7))
min_val = ej3.min()
max_val = ej3.max()
print("\nEjercicio 3.1 - Matriz original:\n", ej3)
print(f"Mínimo: {min_val}, Máximo: {max_val}")


Ejercicio 3.1 - Matriz original:
 [[65 29 15 58 14 96 35]
 [23 75 52  3 90 55 75]
 [91 90 31 90 15 16 69]
 [17 78 94  8 70  9  1]
 [45 26 96 77 23 88 32]
 [82 62 15 65 16 14 23]
 [90 55 98 61 96  5 23]]
Mínimo: 1, Máximo: 98


* Normaliza la matriz anterior entre 0 y 1.

In [41]:
ej3_normalized = (ej3 - min_val) / (max_val - min_val)
print("\nEjercicio 3.2 - Matriz normalizada:\n", ej3_normalized)



Ejercicio 3.2 - Matriz normalizada:
 [[0.65979381 0.28865979 0.1443299  0.58762887 0.13402062 0.97938144
  0.35051546]
 [0.22680412 0.7628866  0.5257732  0.02061856 0.91752577 0.55670103
  0.7628866 ]
 [0.92783505 0.91752577 0.30927835 0.91752577 0.1443299  0.15463918
  0.70103093]
 [0.16494845 0.79381443 0.95876289 0.07216495 0.71134021 0.08247423
  0.        ]
 [0.45360825 0.25773196 0.97938144 0.78350515 0.22680412 0.89690722
  0.31958763]
 [0.83505155 0.62886598 0.1443299  0.65979381 0.15463918 0.13402062
  0.22680412]
 [0.91752577 0.55670103 1.         0.6185567  0.97938144 0.04123711
  0.22680412]]


<center> <h2>Ejercicio 04</h2> </center> 

De la siguiente Matriz

<img src="https://user-images.githubusercontent.com/19308295/115969506-dbbc4b00-a502-11eb-9c76-c9da265c5366.png"
    style="width:400px"></img>

* Luego invertir lo valores de 9 y 1 de la Matriz anterior

In [44]:
import numpy as np

# Crear la matriz original
matriz = np.array([
    [1, 1, 1, 1, 1],
    [1, 0, 0, 0, 1],
    [1, 0, 9, 0, 1],
    [1, 0, 0, 0, 1],
    [1, 1, 1, 1, 1]
])

# Encontrar la posición del 9
pos_9 = np.where(matriz == 9)
i, j = pos_9[0][0], pos_9[1][0]

# Crear una copia para modificar
matriz_modificada = matriz.copy()

# Intercambiar valores: 1 -> 9 y 9 -> 1
matriz_modificada[matriz == 1] = 9  # Cambiar todos los 1 por 9
matriz_modificada[i, j] = 1         # Cambiar la posición original del 9 por 1

print("Matriz original:")
print(matriz)
print("\nMatriz modificada (9 y 1 intercambiados):")
print(matriz_modificada)

Matriz original:
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

Matriz modificada (9 y 1 intercambiados):
[[9 9 9 9 9]
 [9 0 0 0 9]
 [9 0 1 0 9]
 [9 0 0 0 9]
 [9 9 9 9 9]]


<center> <h2>Ejercicio 05</h2> </center> 

De la siguiente Matriz:

<img src="https://user-images.githubusercontent.com/19308295/115969585-39509780-a503-11eb-92ac-fd88557e6cfc.png"
    style="width:400px"></img>

* Extraer la matrices de cada color

In [54]:
import numpy as np

# Crear la matriz 6x5
matriz = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25],
    [26, 27, 28, 29, 30]
])

# Extraer matriz VERDE (columna vertical: 2,8,14,20)
verde = matriz[[0, 1, 2, 3], [1, 2, 3, 4]].reshape(4, 1)

# Extraer matriz ROJA (elementos específicos)
roja = np.array([
    matriz[0, 3:5],    # [4,5]
    matriz[4, 3:5],    # [24,25]
    matriz[5, 3:5]     # [29,30]
])

# Extraer matriz AZUL (submatriz 2x2 superior izquierda)
azul = matriz[2:4, 0:2]  # [11,12] y [16,17]

print("Matriz original:")
print(matriz)
print("\nMatriz VERDE (4x1):")
print(verde)
print("\nMatriz ROJA (3x2):")
print(roja)
print("\nMatriz AZUL (2x2):")
print(azul)

Matriz original:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

Matriz VERDE (4x1):
[[ 2]
 [ 8]
 [14]
 [20]]

Matriz ROJA (3x2):
[[ 4  5]
 [24 25]
 [29 30]]

Matriz AZUL (2x2):
[[11 12]
 [16 17]]


<center> <h2>Ejercicio 06</h2> </center> 

De la siguiente Matriz:

<img src="https://user-images.githubusercontent.com/19308295/115969622-613ffb00-a503-11eb-98b8-7edcf70c5851.png"
    style="width:600px"></img>


Se debe **buscar dentro de la matriz de color verde el valor = 50**, luego reemplazar con la pequeña matriz de color celeste quedando la matriz de la siguiente manera:

<img src="https://user-images.githubusercontent.com/19308295/115969624-656c1880-a503-11eb-9a48-7dba0c379f86.png"
    style="width:400px"></img>


El algoritmo solución debe poder **ubicar el valor = 50** en cualquier posición y hacer el reemplazo.

In [58]:
import numpy as np

# Matriz original 6x6
matriz_grande = np.array([
    [255, 34, 45, 16, 24, 99],
    [200, 56, 67, 15, 50, 88],
    [165, 67, 34, 26, 87, 70],
    [120, 100, 45, 45, 56, 67],
    [45, 50, 35, 67, 225, 44],
    [36, 255, 24, 78, 77, 23]
])

# Matriz celeste de reemplazo (3x3)
matriz_celeste = np.array([
    [0, 0, 0],
    [0, 255, 0],
    [0, 0, 0]
])

# Encontrar todas las posiciones donde el valor es 50
posiciones = np.argwhere(matriz_grande == 50)

# Para cada posición encontrada, reemplazar con la matriz celeste
for pos in posiciones:
    i, j = pos
    # Calcular los límites del bloque 3x3
    fila_inicio = max(0, i - 1)
    fila_fin = min(matriz_grande.shape[0], i + 2)
    col_inicio = max(0, j - 1)
    col_fin = min(matriz_grande.shape[1], j + 2)
    
    # Calcular los límites dentro de la matriz celeste
    sub_i = 1 - (i - fila_inicio)
    sub_j = 1 - (j - col_inicio)
    
    # Reemplazar el bloque en la matriz grande
    bloque = matriz_celeste[
        sub_i:sub_i + (fila_fin - fila_inicio),
        sub_j:sub_j + (col_fin - col_inicio)
    ]
    
    matriz_grande[fila_inicio:fila_fin, col_inicio:col_fin] = bloque

print("Matriz modificada:")
print(matriz_grande)

Matriz modificada:
[[255  34  45   0   0   0]
 [200  56  67   0 255   0]
 [165  67  34   0   0   0]
 [  0   0   0  45  56  67]
 [  0 255   0  67 225  44]
 [  0   0   0  78  77  23]]


![linea 2](https://user-images.githubusercontent.com/19308295/115926262-2fb62980-a448-11eb-8189-c2f10e499944.png)

## <font color=#33A5FF>****BIBLIOGRAFÍA****<tfont>

[1] Documentación de NumPy http://docs.scipy.org/doc/numpy

[2] Travis Oliphant, "Guide to NumPy" http://csc.ucdavis.edu/~chaos/courses/nlp/Software/NumPyBook.pdf

[3] SciPy Lecture Notes http://scipy-lectures.github.io

[4] Nicolas Rougier, "100 NumPy exercises" http://www.loria.fr/~rougier/teaching/numpy.100/index.html

![linea 1](https://user-images.githubusercontent.com/19308295/115926252-2b8a0c00-a448-11eb-9d9c-b43beaf0ff68.png)